### ISSUE TITLE
Not working in Ubuntu 18.04

### ISSUE THREAD

**Issue by tamaraita** [frecel/ScreenRotator#9]
I've installed the packages, then I did

```
tamara@tamara-Inspiron-3593:~$ git clone https://github.com/frecel/ScreenRotatorCloning into 'ScreenRotator'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 76 (delta 1), reused 3 (delta 1), pack-reused 69
Unpacking objects: 100% (76/76), done.
tamara@tamara-Inspiron-3593:~$ cd ScreenRotator
tamara@tamara-Inspiron-3593:~/ScreenRotator$ ./ScreenRotator.py 
Traceback (most recent call last):
  File "./ScreenRotator.py", line 21, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
tamara@tamara-Inspiron-3593:~/ScreenRotator$ 

```

**Comment by henrysting** [comment]
try with "sudo apt install gir1.2-appindicator3-0.1"
